# Generated by Django 5.0.7 on 2024-08-06 00:33

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='media/servicos', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
