# Generated by Django 5.0.7 on 2024-08-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servico_icone_alter_servico_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-cog', 'Engrenagem1'), ('bi bi-gear', 'Engrenagem'), ('ini-stats-up', 'Gráfico'), ('ini-users', 'Usuários'), ('ini-layers', 'Design'), ('ini-mobile', 'Mobile'), ('ini-rocket', 'Foguete')], max_length=24, verbose_name='Ícone'),
        ),
    ]
