# Generated by Django 5.0.7 on 2024-08-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servico_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('dataDeNascimento', models.DateField()),
                ('localOndeTrabalha', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('cidadeDoCurso', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('curso_escolhido', models.CharField(choices=[('aph', 'Curso APH'), ('sbv', 'Curso SBV')], max_length=3)),
                ('obs', models.TextField()),
            ],
        ),
    ]
